export default {
  APP_name: 'OnMove',
  ONBOARDING_title: 'All transports in your pocket',
  ONBOARDING_start: 'Start!',
  USERPROFILE_title: 'Biography',
  USERPROFILE_addVehicle: 'Add vehicle',
  USERPROFILE_addPhoto: 'Add photo',
  STATISTICS_title: 'Statistics',
  STATISTICS_dayly_activity: 'Dayly activity',
  STATISTICS_mets: 'Mets',
  BUTTON_previous: 'Previous',
  BUTTON_next: 'Next',
  BUTTON_save: 'Save',
  BUTTON_cancel: 'Canvel',
  SETTINGS_title: 'Settings',
  SETTINGS_activity: 'Activity Recognition',
  SETTINGS_survey: 'Survey',
  SETTINGS_survey_tittle: 'Health Survey',
  SETTINGS_success: 'Survey saved successfully',
  SETTINGS_error: 'Error! Please try again!',
  ORDER_cancelled: 'Order cancelled',
  ORDER_accepted: 'Order accepted',
  ORDER_end_route: 'Route finished. This will no longer be available to users',
  ORDER_title: 'Orders',
  SIGNIN_title: 'Mobility Service',
  SIGNIN_subtitle: 'Sign in to continue!',
  SIGNIN_email: 'Email ID',
  SIGNIN_password: 'Password',
  SIGNIN_button: 'Sign in',
  SIGNIN_new_user: 'New user?',
  SIGNUP_error: 'An Error Occured While Creating',
  SIGNUP_success: 'User successfully registered!',
  SIGNUP_title: 'Sign Up',
  SIGNUP_removeImage: 'Remove Image',
  SIGNUP_uploadImage: 'Upload Image',
  SIGNUP_name: 'Name',
  SIGNUP_email: 'Email',
  SIGNUP_password: 'Password',
  SIGNUP_biography: 'Biography',
  SIGNUP_biography_placeholder: 'Something about yourself',
  SIGNUP_contact: 'Contact',
  SIGNUP_birthday: 'Birth Date',
  SIGNUP_body_mass: 'Body Mass',
  SIGNUP_height: 'Height',
  SIGNUP_button: 'Create Account',
  SIGNUP_signIn: 'Already have an account?',
  ACTIVITYMODULE_show_all_records: 'Show all records',
  ACTIVITYMODULE_delete_all_records: 'Delete all records',
  ACTIVITYMODULE_reset_db: 'Database reseted',
  CREATECARPOOLING_needs_vehicle:
    'You need to create a vehicle to introduce a ride',
  CREATECARPOOLING_cancel: 'Cancel',
  CREATECARPOOLING_add_vehicle: 'Create a Vehicle',
  CREATECARPOOLING_missing_information: 'There is missing information!',
  CREATECARPOOLING_success: 'Ride created with success!',
  CREATECARPOOLING_error: 'Error on creating new ride. Please try Again!',
  CREATECARPOOLING_title: 'Create a Car Pooling',
  CREATECARPOOLING_estimatedTime: 'Estimated Time',
  CREATECARPOOLING_alert: 'Reach the minimum value of 10 minutes!',
  CREATECARPOOLING_create: 'Create',
  CREATECARPOOLING_startTime: 'Start Time',
  CREATEVIHECLE_car_model_alert: 'You need to add the Car Model',
  CREATEVIHECLE_success_alert: 'Vehicle created',
  CREATEVIHECLE_error_alert: 'Error on new vehicle. Please try Again!',
  CREATEVIHECLE_title: 'Create Vehicle',
  CREATEVIHECLE_car_model_placeholder: 'Car Model',
  CREATEVIHECLE_limit_alert: 'Minimum vehicle capacity is 2',
  CREATEVIHECLE_button: 'Create',
  CREATECARPOOLING_description: 'Description',
  HOME_dropdown_car: 'Car',
  GERAL_minutes: 'minutes',
  GERAL_error: 'An error occurred!',
  GERAL_created: 'Created',
  GERAL_start: 'Start:',
  GERAL_end: 'End:',
  GERAL_time: 'Estimated time:',
  DESTINATIONDETAIL_start_date: 'Start Date:',
  DESTINATIONDETAIL_available_seats_car: 'Available seats on car:',
  DESTINATIONDETAIL_available_seats: 'Available seats:',
  DESTINATIONDETAIL_description: 'Description:',
  DESTINATIONDETAIL_show_route: 'Show route',
  DESTINATIONDETAIL_go: 'Go',
  DESTINATIONSEARCH_error_alert: 'Error! Please try again later!',
  DESTINATIONSEARCH_no_routes_alert: 'No routes available',
  HOME_error_inputs:
    'Start Location and End Location are the same! Please change!',
  HOME_dropdown_placeholder: 'Where you want to go?',
  HOME_next_travel: 'Your next travel',
  HOME_title: 'Search routes',
  HOME_dropdown_placeholder_start: 'Starting point:',
  HOME_dropdown_placeholder_end: 'Destination:',
  HOME_search: 'Search',
  HOME_recommended: 'Near you:',
  HOME_initial: 'Initial location',
  HOME_final: 'Final location',
  HOME_initial_button: 'Set initial location',
  HOME_final_button: 'Set final location',
  NAVIGATION_home: 'Home',
  NAVIGATION_requests: 'Requests',
  NAVIGATION_settings: 'Settings',
  NAVIGATION_stats: 'Statistics',
  NAVIGATION_signout: 'Sign out',
  SEND: 'Send',
};
