export default {
  APP_name: 'Mobility One',
  ONBOARDING_title: 'Todos os transportes no seu bolso',
  ONBOARDING_start: 'Iniciar!',
  SIGNIN_title: 'Serviço de Mobilidade',
  SIGNIN_subtitle: 'Faça login para continuar!',
  SIGNIN_email: 'Email',
  SIGNIN_password: 'Password',
  SIGNIN_button: 'Login',
  SIGNIN_new_user: 'Novo utilizador?',
  SIGNUP_error: 'Ocorreu um erro ao criar',
  SIGNUP_success: 'Utilizador criado com sucesso!',
  SIGNUP_title: 'Registar',
  SIGNUP_removeImage: 'Remover Imagem',
  SIGNUP_uploadImage: 'Carregar Imagem',
  SIGNUP_name: 'Nome',
  SIGNUP_email: 'Email',
  SIGNUP_password: 'Password',
  SIGNUP_biography: 'Biografia',
  SIGNUP_biography_placeholder: 'Algo sobre si mesmo',
  SIGNUP_contact: 'Contacto',
  SIGNUP_birthday: 'Data de Nascimento',
  SIGNUP_body_mass: 'Peso',
  SIGNUP_height: 'Altura',
  SIGNUP_button: 'Registar',
  SIGNUP_signIn: 'Já tem uma conta?',
};
