export default {
  APP_name: 'Mobility One',
  ONBOARDING_title: 'Todos os transportes no seu bolso',
  ONBOARDING_start: 'Iniciar!',
  USERPROFILE_title: 'Biografia',
  STATISTICS_title: 'Estatísticas',
  STATISTICS_dayly_activity: 'Atividade diária',
  BUTTON_previous: 'Anterior',
  BUTTON_next: 'Próximo',
  SETTINGS_title: 'Configurações',
  SETTINGS_activity: 'Reconhecimento de atividade',
  SETTINGS_survey: 'Questionário de saúde',
  ORDER_cancelled: 'Cancelado',
  ORDER_accepted: 'Aceite',
  ORDER_end_route:
    'Rota finalizada. Esta não será mais disponível para os utilizadores',
  ORDER_title: 'Pedidos',
  SIGNIN_title: 'Serviço de Mobilidade',
  SIGNIN_subtitle: 'Faça login para continuar!',
  SIGNIN_email: 'Email',
  SIGNIN_password: 'Password',
  SIGNIN_button: 'Login',
  SIGNIN_new_user: 'Novo utilizador?',
  SIGNUP_error: 'Ocorreu um erro ao criar',
  SIGNUP_success: 'Utilizador criado com sucesso!',
  SIGNUP_title: 'Registar',
  SIGNUP_removeImage: 'Remover Imagem',
  SIGNUP_uploadImage: 'Carregar Imagem',
  SIGNUP_name: 'Nome',
  SIGNUP_email: 'Email',
  SIGNUP_password: 'Password',
  SIGNUP_biography: 'Biografia',
  SIGNUP_biography_placeholder: 'Algo sobre si mesmo',
  SIGNUP_contact: 'Contacto',
  SIGNUP_birthday: 'Data de Nascimento',
  SIGNUP_body_mass: 'Peso',
  SIGNUP_height: 'Altura',
  SIGNUP_button: 'Registar',
  SIGNUP_signIn: 'Já tem uma conta?',
  ACTIVITYMODULE_show_all_records: 'Mostrar todos os registos',
  ACTIVITYMODULE_delete_all_records: 'Apagar todos os registos',
  ACTIVITYMODULE_reset_db: 'Base de dados apagada',
  CREATECARPOOLING_needs_vehicle:
    'Precisa de um veículo para poder criar uma boleia',
  CREATECARPOOLING_cancel: 'Cancelar',
  CREATECARPOOLING_add_vehicle: 'Criar um veículo',
  CREATECARPOOLING_missing_information: 'Existem campos em falta',
  CREATECARPOOLING_success: 'Boleia criada com sucesso!',
  CREATECARPOOLING_error: 'Erro ao criar boleia. Tente novamente',
  CREATECARPOOLING_title: 'Criar uma boleia',
  CREATECARPOOLING_estimatedTime: 'Tempo estimado',
  CREATECARPOOLING_alert: 'Assegura no minimo 10 minutos!',
  CREATECARPOOLING_create: 'Criar',
  CREATECARPOOLING_startTime: 'Começou a:',
  CREATEVIHECLE_car_model_alert: 'Adicione um modelo de veículo',
  CREATEVIHECLE_success_alert: 'Veículo criado com sucesso!',
  CREATEVIHECLE_error_alert: 'Erro ao criar veículo. Tente novamente',
  CREATEVIHECLE_title: 'Criar',
  CREATEVIHECLE_car_model_placeholder: 'Modelo do veículo',
  CREATEVIHECLE_limit_alert: 'Capacidade minima de veículo é 2',
  CREATEVIHECLE_button: 'Criar',
  CREATEVIHECLE_capacity: 'Capacidade',
  CREATECARPOOLING_description: 'Descrição',
  HOME_dropdown_car: 'Veículos',
  GERAL_minutes: 'minutos',
  GERAL_error: 'Occoreu um erro!',
  GERAL_created: 'Criado',
  GERAL_start: 'Iniciou:',
  GERAL_end: 'Fim:',
  GERAL_time: 'Tempo estimado:',
  DESTINATIONDETAIL_start_date: 'Data inicio:',
  DESTINATIONDETAIL_available_seats_car: 'Assentos disponiveis no veiculo:',
  DESTINATIONDETAIL_available_seats: 'Assentos disponiveis:',
  DESTINATIONDETAIL_description: 'Descrição:',
  DESTINATIONDETAIL_show_route: 'Mostrar rota',
  DESTINATIONDETAIL_go: 'Ir',
  DESTINATIONSEARCH_error_alert: 'Erro ao procurar destinos. Tente novamente',
  DESTINATIONSEARCH_no_routes_alert: 'Sem rotas disponiveis',
  HOME_error_inputs:
    'Localização incial e final não podem ser iguais. Tente novamente',
  HOME_dropdown_placeholder: 'Onde deseja ir:',
  HOME_next_travel: 'Próximo viagem:',
  HOME_title: 'Pesquisar rota',
  HOME_dropdown_placeholder_start: 'Onde está:',
  HOME_dropdown_placeholder_end: 'Onde deseja ir:',
  HOME_search: 'Pesquisar',
  HOME_recommended: 'Perto de si:',
  NAVIGATION_home: 'Inicio',
  NAVIGATION_requests: 'Pedidos',
  NAVIGATION_settings: 'Configurações',
  NAVIGATION_stats: 'Estatísticas',
  SEND: 'Enviar',
};
