name: deploy auth
on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy auth
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/tecnicoesce/Documentos/MobilityOne
          git pull
          cd auth
          npm run build
          pm2 reload auth
