name: deploy routes
on:
  push:
    branches:
      - master
    paths:
      - 'routes/**'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/tecnicoesce/Documentos/MobilityOne
          git pull
          pm2 reload routes

